### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ghost** [mbilsky/TeensyADS1256#1]
Hello there,
I just started going through your library and adapting it for my own purposes, I think you have a type on line 128 of ADSconstants, there's a non-digit character in the #define

#define DIR1_IN   B001**ßß**000 //D1 is an input (default)

**Comment by mbilsky** [comment]
Thanks. I just updated it. According to the datasheet they should be zero not beta. The error is also present in flydroid's original library.

Thanks for letting me know!

**Comment by ghost** [comment]
Cheer
I'll send you a copy of the library I end up with, probably going to morph it into a true "library" that is importable. Thanks for all the hard work!

**Comment by mbilsky** [comment]
Sounds great!

Happy to discuss if you have issues and can also link to it in the videos, etc.

Thanks,
Matt

**Comment by mbilsky** [comment]
something that I've considered is the notion of multi-threading the system since there are a lot of delays needed for it to work correctly.

I just did a quick google search: https://forum.pjrc.com/threads/41504-Teensy-3-x-multithreading-library-first-release

Thoughts?

**Comment by ghost** [comment]
Yea it looks great that would be great to implement. I use a teensy 3.5,
and multithreading is something I’ve always wanted to investigate. Would
add a lot more capability to teensy and useful for other projects too. I’ll
let you know if I make any progress in that regard.

Are you thinking about processing the data in a parallel thread? Curious
because the ADC1256 operations are sequential so not sure what
multithreading buys us

**Comment by mbilsky** [comment]
I was thinking about sending/receiving commands in a parallel thread behind the scenes of what’s happening in the foreground (running a controller, changing pins, etc.) since a decent amount of time is spent in delays. It would be nice to be able to do other things during those delays.

Just an idea that I haven’t really baked out yet since I haven’t had an explicit need for it

Matt Bilsky, PhD, PE
Post-Doc, Adjunct Professor, Innovator, and Entrepreneur
Department of Mechanical Engineering, Lehigh University
Founder, Impossible Incorporated LLC
http://mattbilsky.com<https://urldefense.proofpoint.com/v2/url?u=http-3A__mattbilsky.com_&d=DwMGaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=UDZcGPNAFyTWPyihSrfMNtEpcMK0GrHlrey3K-01zWM&m=jNXxXtA7gLE9cFKums-P_HMVbDwvExHonwqhqzMXCEc&s=x1TgyVfmwSS-RIXvkAqQ7RgTM4as8jEmN8g8Qyg6RwU&e=>

**Comment by ghost** [comment]
Gotcha, yes it would be nice to do other useful work during the delays. It
will be necessary to look at what the “time slice” is for the
multithreading library. If it’s longer than a delay it would screw up the
bit timing, if not, then definitely is something that should be done and is
the preferred option

Another option is to use the teensy interval timer which uses interrupts .

Nice work.
What sort of offsets do you see on the 1256 after performing a self cal?

**Comment by mbilsky** [comment]
Yes to both. I considered that but to everything, not sure how much time it will save since we’re delaying uS in the first place (and can run 30KSPS). I think one would see the savings if you had multiple ADS1256 or SPI devices on 2 different busses (such as on the 3.5 or 3.6).

I have not investigated the offset between different self-cals. Good food for thought

Matt Bilsky, PhD, PE
Post-Doc, Adjunct Professor, Innovator, and Entrepreneur
Department of Mechanical Engineering, Lehigh University
Founder, Impossible Incorporated LLC
http://mattbilsky.com<https://urldefense.proofpoint.com/v2/url?u=http-3A__mattbilsky.com_&d=DwMGaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=UDZcGPNAFyTWPyihSrfMNtEpcMK0GrHlrey3K-01zWM&m=jNXxXtA7gLE9cFKums-P_HMVbDwvExHonwqhqzMXCEc&s=x1TgyVfmwSS-RIXvkAqQ7RgTM4as8jEmN8g8Qyg6RwU&e=>

**Comment by ghost** [comment]
Heya Matt,
Just had time to start working on this again. My laptop that had all my
code on it got stolen! Its ok though, just bought another one and def going
to keep all important code on github now.

So just started going through the library again and noticed something I
should tell you. At least on my wingoneer board, the voltage reference was
an ADR03 chip, which had a vref of 2.5 volts. The library is coded as a 5v
value however. So it may make your readings off by a factor of 2 if you
have the same board as me.

I'm not a huge fan of the ADR03 so I replaced it with LTC6655, and replaced
the buffer amp with OPA227 to get a quieter reference.  Also separated the
power supply to the board from the microcontroller, and gave it a quiet
reference voltage. The noise of my readings immediately went down
afterwards. Anyways just a couple ideas if youre interested.

​

**Comment by mbilsky** [comment]
Hi There,

Sounds like a rough few days!

The VREF is supposed to be 2.5 volts for the ADS1256 (see page 3 of the datasheet)

As for the other 2 changes, if they helped that’s great! Did you spin up your own PCB?

What I like about the current solution is that it is a stock assembly rather than something I need to put together.

I’d be curious to run the same tests I did previously to see how they compare head to head.

Thanks,
Matt

Matt Bilsky, PhD, PE
Post-Doc, Adjunct Professor, Innovator, and Entrepreneur
Department of Mechanical Engineering, Lehigh University
Founder, Impossible Incorporated LLC
http://mattbilsky.com<https://urldefense.proofpoint.com/v2/url?u=http-3A__mattbilsky.com_&d=DwMGaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=UDZcGPNAFyTWPyihSrfMNtEpcMK0GrHlrey3K-01zWM&m=jNXxXtA7gLE9cFKums-P_HMVbDwvExHonwqhqzMXCEc&s=x1TgyVfmwSS-RIXvkAqQ7RgTM4as8jEmN8g8Qyg6RwU&e=>
